Game logic
rociac/tic-tac-toe pull request #2
Opened 2019-08-13 22:03 UTC by rociac

2019-08-13 22:41 UTC, allun26 commented
We have fixed most of the linter errors but some of them doesn't make sense, like these:

> lib/game.rb#L30
> C: Layout/IndentationWidth: Use 2 (not -16) spaces for indentation.
>  Check failure on line 31 in lib/game.rb

-16 indentation? 

> lib/game.rb#L31
> C: Layout/ElseAlignment: Align `else` with `if`.

This is a bit weird aswell as it will make the code look ugly.

2019-08-14 00:05 UTC, JamesOkunlade requested changes
### Hello @rociac  and @allun26 

Great work so far :sunglasses: Your game logic is beautiful and the game is playing very well. I have few observations though. :slightly_smiling_face:
- The linter is to enforce best practices as a professional so it's important to ensure no check is failing before moving forward. I left some comments in different lines of your `game.rb` file that could improve your code.
- Also, single responsibility of method is very important and that's why it would be better if you can separate your `win_check` method further by having a `winner` method that checks who the winner is as you have it in your code. `win_check` should only be winning combinations.

Your work will be perfect if those two important points are fixed. Take more time to work on fixing these points and request a re-review when you're done.

Happy coding devs!! :v:

2019-08-14 00:05 UTC, JamesOkunlade commented on lib/game.rb
> +    @current_player = if @current_player == 1
You can refactor this whole expression using ruby ternary operator then you'll have: 
`@current_player = @current_player == 1 ? 2 : 1` This will fix the linting issue as well.

2019-08-14 00:05 UTC, JamesOkunlade commented on lib/game.rb
> +    @winner = if @current_player == 2
It's best you separate this into a different method on its own. Say `@winner` to ensure each method follows the single responsibility rule. When creating this method, you could use the ternary expression as well.

2019-08-14 16:35 UTC, rociac commented
We have made the required changes, project is finished. Looking forward for your feedback!

2019-08-14 17:47 UTC, AdnanAfsari commented
### **ADNAN AFSARI WORKING ON IT**

2019-08-14 17:53 UTC, AdnanAfsari approved these changes
Hello @rociac @allun26 👍 

Nice work guys , i think you have made all the changes that the previous reviewer requested 😄 
so its a 👍 for me.

Happy Coding

2019-08-14 19:01 UTC, rociac commented
Hi, we are submitting this again, because i submitted it at first for the wrong project. Project is already finished.

2019-08-14 19:38 UTC, JamesOkunlade approved these changes
Hello Devs!!

I'm not sure what you meant by the comment above. This milestone 2 `game_logic` has been approved by the previous reviewer. You should go ahead and merge it to `dev`.  I see you have updated your README.md file as well :grin: you were supposed to raise a different feature branch for it i.e. `milestone 3` but it's okay since you already did that in `milestone 2`. Ensure to stick to `git-flow`  and stick to the `milestones` if provided in your future project.

Please merge and close the pull request. Good luck with your future projects. :v:

2019-08-14 19:47 UTC, merged